from collections import defaultdict
import yaml
from pprint import pprint

# Load the YAML content to process
file_path = "./app/content/firetruck_tools.yaml"

# Loading the YAML file
with open(file_path, "r", encoding="utf-8") as file:
    data = yaml.safe_load(file)


# Normalize function: To handle common differences (case, whitespace, hyphens)
def normalize_string(s):
    return (
        s.lower()
        .replace(" ", "")
        .replace("-", "")
        .replace("ü", "u")
        .replace("ä", "a")
        .replace("ö", "o")
        .replace("ß", "ss")
    )


# Dictionary to store normalized names with their original strings
items_dict = defaultdict(list)


# Traverse YAML data recursively to collect item names
def collect_items(data, items_dict):
    if isinstance(data, dict):
        for value in data.values():
            collect_items(value, items_dict)
    elif isinstance(data, list):
        for item in data:
            normalized = normalize_string(item)
            items_dict[normalized].append(item)


# Run the function on the loaded data
collect_items(data, items_dict)

# Find items with different descriptions by checking if there are multiple original strings for a normalized string
# inconsistent_items = {key: set(val) for key, val in items_dict.items() if len(val) > 1}
inconsistent_items = {key: set(val) for key, val in items_dict.items()}

pprint(inconsistent_items, width=100)

result = {
    "a2sanitatsrucksack": {"A2-Sanitätsrucksack"},
    "abckupplungsschlussel": {"ABC-Kupplungsschlüssel", "ABC Kupplungsschlüssel"},
    "abcpulverloscher": {"ABC Pulverlöscher", "ABC-Pulverlöscher"},
    "abdeckplane": {"Abdeckplane"},
    "abfullschaufelnf.olbindemittel": {"Abfüllschaufeln f. Ölbindemittel"},
    "abgasschlauch": {"Abgasschlauch"},
    "abschleppseil": {"Abschleppseil"},
    "abschleppseil12mm5m": {"Abschleppseil 12 mm 5 m"},
    "abschleppseil16mm5m": {"Abschleppseil 16 mm 5 m"},
    "abschleppstange": {"Abschleppstange"},
    "absperrband": {"Absperrband"},
    "absperrpfropfen": {"Absperrpfropfen"},
    # next
    "absperrschieberb": {"Absperrschieber B"},
    "absperrschlusself.gas": {"Absperrschlüssel f. Gas"},
    "absperrschlusself.hauswasser": {"Absperrschlüssel f. Hauswasser"},
    "absperrschlusselhauswasser": {"Absperrschlüssel Hauswasser"},
    "absperrstander": {"Absperrständer"},
    "absperrstange": {"Absperrstange"},
    "absperrstangen": {"Absperrstangen"},
    "absturzsicherungsgerat": {"Absturzsicherungsgerät"},
    "abstutzsystem": {"Abstützsystem"},
    "adalitlampe": {"Adalitlampe"},
    "adapter7/13pol": {"Adapter 7/13-Pol"},
    "aggregatf.hydr.rettungssatz": {"Aggregat f. hydr. Rettungssatz"},
    "airbagsafe": {"Airbagsafe"},
    "airbagsicherung": {"Airbag Sicherung"},
    "akkuf.sabelsage": {"Akku f. Säbelsäge"},
    "akkukombigerat": {"Akku Kombigerät"},
    "akkuladegerat": {"Akkuladegerät"},
    "akkuschere": {"Akku Schere"},
    "akkuspreizer": {"Akku Spreizer"},
    "akkuzylinder": {"Akku Zylinder"},
    "aluminiumrandschaufel": {"Aluminium Randschaufel"},
    "alurettungsdecke": {"Alu-Rettungsdecke"},
    "aluschaufel": {"Alu-Schaufel"},
    "anhaltekelle": {"Anhaltekelle"},
    "anhaltestab": {"Anhaltestab"},
    "anhangekupplungkugelkopf": {"Anhängekupplung Kugelkopf"},
    "anhangekupplungmaulkupplung": {"Anhängekupplung Maulkupplung"},
    "arbeitsleine": {"Arbeitsleine"},
    "arbeitsleine30m": {"Arbeitsleine 30 m"},
    "arbeitsmesser": {"Arbeitsmesser"},
    "asaugkorbm.ruckschlagventil": {"A-Saugkorb m. Rückschlagventil"},
    "asaugschlauch": {"A-Saugschlauch"},
    "atemluftflasche300bar": {"Atemluftflasche 300 bar"},
    "atemschutzfilter": {"Atemschutzfilter"},
    "atemschutzmaske": {"Atemschutzmaske"},
    "atemschutzmaskem.filter": {"Atemschutzmaske m. Filter"},
    "atemschutztisch": {"Atemschutztisch"},
    "atemschutzuberwachungstafel": {"Atemschutz Überwachungstafel"},
    "auffangbehalter": {"Auffangbehälter"},
    "auffangbehalter30l": {"Auffangbehälter 30 l"},
    "auffangmulden": {"Auffangmulden"},
    "auffangplane3x4m": {"Auffangplane 3x4 m"},
    "auffangsackspillpacks": {"Auffangsack Spillpacks"},
    "auffangtank1500l": {"Auffangtank 1500 l"},
    "auffangwanne150l": {"Auffangwanne 150 l"},
    "auffangwannem.ausguss": {"Auffangwanne m. Ausguss"},
    "aufnahmebruckef.fluter": {"Aufnahmebrücke f. Fluter"},
    "aufnahmef.korbtrage": {"Aufnahme f. Korbtrage"},
    "aufsatzf.rodator": {"Aufsatz f. Rodator"},
    "ausgiessstutzen": {"Ausgießstutzen"},
    "ausraumhaken": {"Ausräumhaken"},
    "autooffnungswerkzeug": {"Auto-Öffnungswerkzeug"},
    "axt": {"Axt"},
    "bandschlinge22kn": {"Bandschlinge 22 kN"},
    "bandschlingef.pkwosen": {"Bandschlinge f. PKW-Ösen"},
    "basisausrustungobfv": {"Basisausrüstung ÖBFV"},
    "basisausrustungz.haltenv.personen": {"Basisausrüstung z. Halten v. Personen"},
    "basissichern/auffangen": {"Basis Sichern/Auffangen"},
    "baufolie4x4m": {"Baufolie 4 x 4 m"},
    "baumschoner": {"Baumschoner"},
    "bdruckschlauch": {"B-Druckschlauch"},
    "beleuchtungssystemrls2000": {"Beleuchtungssystem RLS2000"},
    "benzinkanister": {"Benzinkanister"},
    "benzinkanister10l": {"Benzinkanister 10 l", "Benzin-Kanister 10 l"},
    "benzinkanister20l": {"Benzin-Kanister 20 l", "Benzinkanister 20 l"},
    "bergetuch": {"Bergetuch"},
    "besen": {"Besen"},
    "beu.entluftungsgerat": {"Be- u. Entlüftungsgerät"},
    "bindedraht": {"Bindedraht"},
    "bindedrahtverzinkt": {"Bindedraht verzinkt"},
    "bindefliesrolle": {"Bindeflies Rolle"},
    "bindeleine6m": {"Bindeleine 6 m"},
    "bindemittelstreuwagen": {"Bindemittel Streuwagen"},
    "blindkupplungenf.olsperre": {"Blindkupplungen f. Ölsperre"},
    "blitzerled": {"Blitzer LED"},
    "blitzleuchten": {"Blitzleuchten"},
    "bmehrzweckstrahlrohr": {"B-Mehrzweckstrahlrohr"},
    "bodenteller": {"Bodenteller"},
    "bodentellerf.absperrstander": {"Bodenteller f. Absperrständer"},
    "bodentellerf.absperrstangen": {"Bodenteller f. Absperrstangen"},
    "bogensage": {"Bogensäge"},
    "bohrhammer": {"Bohrhammer"},
    "bolzenf.umlenkrolle": {"Bolzen f. Umlenkrolle"},
    "bolzenschneider": {"Bolzenschneider"},
    "bolzenschneider75cm": {"Bolzenschneider 75 cm"},
    "bordwerkzeug": {"Bordwerkzeug"},
    "brandfluchthaube": {"Brandfluchthaube"},
    "brecheisen": {"Brecheisen"},
    "brecheisen70cm": {"Brecheisen 70 cm"},
    "brechstange": {"Brechstange"},
    "brechstange1,4m": {"Brechstange 1,4 m"},
    "brechstange1,5m": {"Brechstange 1,5 m"},
    "brechstange1,7m": {"Brechstange 1,7 m"},
    "brechstangelang1,5m": {"Brechstange lang 1,5 m"},
    "breithaue": {"Breithaue"},
    "brust/sitzgurtm.1,5mleine": {"Brust-/Sitzgurt m. 1,5 m Leine"},
    "bstutzkrummer": {"B-Stützkrümmer"},
    "bverbindungsschlauch": {"B-Verbindungsschlauch"},
    "cafsloscher10l": {"CAFS Löscher 10 l"},
    "cdruckschlauch": {"C-Druckschlauch"},
    "chemiehandschuhe": {"Chemiehandschuhe"},
    "chemieschutzanzug": {"Chemieschutzanzug"},
    "chemieschutzanzugmitstiefel": {"Chemieschutzanzug mit Stiefel"},
    "chemieschutzanzugstufe2": {"Chemieschutzanzug Stufe 2"},
    "chemieschutzhandschuhe": {"Chemieschutzhandschuhe"},
    "chemieschutzstiefel": {"Chemieschutzstiefel"},
    "chemischebindemittel": {"Chemische Bindemittel"},
    "chemischeschutzhandschuhe": {"Chemische Schutzhandschuhe"},
    "chohlstrahlrohr": {"C-Hohlstrahlrohr"},
    "cmehrzweckstrahlrohr": {"C-Mehrzweckstrahlrohr"},
    "co2loscher": {"CO2 Löscher"},
    "cschlauchpaketm.absperrhahn": {"C-Schlauchpaket m. Absperrhahn"},
    "cstrahlrohr": {"C-Strahlrohr"},
    "decke": {"Decke"},
    "deckelabzieher": {"Deckelabzieher"},
    "deckenstutzen": {"Deckenstützen"},
    "dekontaminationswanne": {"Dekontaminationswanne"},
    "dekowanne": {"Dekowanne"},
    "dichtkeil": {"Dichtkeil"},
    "dichtpfropfen": {"Dichtpfropfen"},
    "dichtungsband": {"Dichtungsband"},
    "dieselkanister": {"Dieselkanister"},
    "dieselkanister20l": {"Diesel-Kanister 20 l", "Dieselkanister 20 l"},
    "doppelaxt": {"Doppelaxt"},
    "doppelmembranpumpe": {"Doppelmembran Pumpe"},
    "doppelsteuerorganhebekissen": {"Doppelsteuerorgan Hebekissen"},
    "doppelwirkenderrettungszylinder": {"Doppelwirkender Rettungszylinder"},
    "drahtschutzkorb": {"Drahtschutzkorb"},
    "drahtseilkemmen": {"Drahtseilkemmen"},
    "drahtseilverzinkt10m": {"Drahtseil verzinkt 10 m"},
    "drahtseilverzinkt5m": {"Drahtseil verzinkt 5 m"},
    "drahtstift": {"Drahtstift"},
    "dreibeinstativ": {"Dreibeinstativ"},
    "dreieckschlussel": {"Dreieck-Schlüssel"},
    "druckbegrenzungsventil": {"Druckbegrenzungsventil"},
    "druckbegrenzungsventilb": {"Druckbegrenzungsventil B"},
    "druckbelufter": {"Druckbelüfter"},
    "druckbeluftungsgerat": {"Druckbelüftungsgerät"},
    "druckloschgeratbioversal": {"Drucklöschgerät Bioversal"},
    "drucklufter": {"Drucklüfter"},
    "druckluftflaschef.hebekissen": {"Druckluftflasche f. Hebekissen"},
    "druckluftschlauch20m": {"Druckluftschlauch 20m"},
    "druckschlauchb": {"Druckschlauch B"},
    "druckschlauchb7520m": {"Druckschlauch B75 20 m"},
    "druckschlauchb7525morange": {"Druckschlauch B75 25 m orange"},
    "druckschlauchc": {"Druckschlauch C"},
    "druckschlauchc42": {"Druckschlauch C42"},
    "druckschlauchc5215m": {"Druckschlauch C52 15 m"},
    "druckschlauchc7m": {"Druckschlauch C 7 m"},
    "druckschlauchhd": {"Druckschlauch HD"},
    "dsaugschlauchfurpumpenvormischer": {"D-Saugschlauch für Pumpenvormischer"},
    "dunggabel": {"Dunggabel"},
    "dungkralle": {"Dungkralle"},
    "durchzugsnadel": {"Durchzugsnadel"},
    "eckrohrzangekleinfunkenfrei": {"Eckrohrzange klein funkenfrei"},
    "egummimatte": {"E-Gummimatte"},
    "einbaugenerator10kva": {"Einbaugenerator 10 kVA"},
    "einbruchwerkzeug": {"Einbruchwerkzeug"},
    "einfullstutzen": {"Einfüllstutzen"},
    "einhangefolief.faltbehalter": {"Einhängefolie f. Faltbehälter"},
    "einlaufkrummerb": {"Einlaufkrümmer B"},
    "einreisshaken": {"Einreißhaken"},
    "einweghandschuhe": {"Einweghandschuhe"},
    "einzelsteuerorganhebekissen": {"Einzelsteuerorgan Hebekissen"},
    "eisensage": {"Eisensäge"},
    "elektrokettensage": {"Elektrokettensäge"},
    "elektrorettungshaken": {"Elektrorettungshaken"},
    "elektrowerkzeug": {"Elektrowerkzeug"},
    "elektrowerkzeugsatz": {"Elektrowerkzeugsatz"},
    "emotorsage": {"E-Motorsäge"},
    "endlosschlinge60kn3m": {"Endlosschlinge 60 kN 3 m"},
    "endlosschlingeblau8t": {"Endlosschlinge blau 8 t"},
    "endstuckbefestigungkranarm": {"Endstückbefestigung Kranarm"},
    "entfernungsmesser": {"Entfernungsmesser"},
    "erdanker": {"Erdanker"},
    "erdspiess": {"Erdspieß"},
    "erdspiessef.freilandverankerung": {"Erdspieße f. Freilandverankerung"},
    "erdungskabel": {"Erdungskabel"},
    "erdungsklemmenfunkenfrei": {"Erdungsklemmen funkenfrei"},
    "erdungslitze": {"Erdungslitze"},
    "erdungsschiene": {"Erdungsschiene"},
    "erdungsspiess": {"Erdungsspieß"},
    "erdungsspiessfunkenfrei": {"Erdungsspieß funkenfrei"},
    "erdungszwingen": {"Erdungszwingen"},
    "ersatzbackenrettungsspreizer": {"Ersatzbacken Rettungsspreizer"},
    "ersatzkettef.motorkettensage": {"Ersatzkette f. Motorkettensäge"},
    "ersatzkettef.motorsage": {"Ersatzkette f. Motorsäge"},
    "ersatzketterettungssage": {"Ersatzkette Rettungssäge"},
    "ersatzmesserrettungsschere": {"Ersatzmesser Rettungsschere"},
    "ersatztrennscheiben": {"Ersatztrennscheiben"},
    "erstehilfekoffer": {"Erste-Hilfe-Koffer"},
    "erstehilferucksack": {"Erste-Hilfe Rucksack"},
    "euroblitzleuchte": {"Euroblitzleuchte", "Euro-Blitz Leuchte"},
    "europaabsperrband": {"Europa Absperrband"},
    "ewerkzeug": {"E-Werkzeug"},
    "fahrzeugunterlegkeile": {"Fahrzeug Unterlegkeile"},
    "fahrzeugwerkzeug": {"Fahrzeugwerkzeug"},
    "faltbehalter": {"Faltbehälter"},
    "faltbehalter3000l": {"Faltbehälter 3000 l"},
    "fass/universalschlusselfunkenfrei": {"Fass-/Universalschlüssel funkenfrei"},
    "fassbundoffner": {"Fassbundöffner"},
    "fassschaufel": {"Fassschaufel"},
    "fassschlussel": {"Fassschlüssel"},
    "federkorner": {"Federkörner"},
    "fernsteuerungf.suchscheinwerferamheck": {
        "Fernsteuerung f. Suchscheinwerfer am Heck"
    },
    "fettbrandloscher": {"Fettbrandlöscher"},
    "feuerloscher": {"Feuerlöscher"},
    "feuerloscherp12": {"Feuerlöscher P12"},
    "feuerloscherp6": {"Feuerlöscher P6"},
    "feuerpatsche": {"Feuerpatsche"},
    "feuerwehrauffanggurt": {"Feuerwehrauffanggurt"},
    "feuerwehraxt": {"Feuerwehraxt"},
    "feuerwehrbeil": {"Feuerwehrbeil"},
    "feuerwehrgurt": {"Feuerwehrgurt"},
    "feuerwehrhandschuhe": {"Feuerwehrhandschuhe"},
    "feuerwehrsappel": {"Feuerwehrsappel"},
    "ffp2maske": {"FFP2-Maske"},
    "filteratemschutz": {"Filteratemschutz"},
    "fixeingebautekabeltrommel": {"Fixeingebaute Kabeltrommel"},
    "flachansauger": {"Flachansauger"},
    "flachschaufel": {"Flachschaufel"},
    "flammschutzbekleidung": {"Flammschutzbekleidung"},
    "flankierer": {"Flankierer"},
    "flatterleine5m": {"Flatterleine 5 m"},
    "fluchthaube": {"Fluchthaube"},
    "flutbrucke": {"Flutbrücke"},
    "fluter1500w": {"Fluter 1500 W"},
    "fluterbrucke": {"Fluterbrücke"},
    "flutlichtscheinwerfer1000w": {"Flutlichtscheinwerfer 1000 W"},
    "fognail": {"Fognail"},
    "forceaxt": {"Force Axt"},
    "forstarbeiterhelm": {"Forstarbeiterhelm"},
    "forsthelm": {"Forsthelm"},
    "forstkeil": {"Forstkeil"},
    "freilandverankerung": {"Freilandverankerung"},
    "fremdbetankungsgarnitur": {"Fremdbetankungs-Garnitur"},
    "funkbedienunglichtmast": {"Funkbedienung Lichtmast"},
    "funkfernbedienunglichtmast": {"Funkfernbedienung Lichtmast"},
    "fusstaster": {"Fußtaster"},
    "fussteilf.kantenreiter": {"Fussteil f. Kantenreiter"},
    "fwdoppelaxt": {"FW-Doppelaxt"},
    "fweinsatzhandschuhe": {"FW-Einsatzhandschuhe"},
    "fwgurt": {"FW-Gurt"},
    "gasmessgerat": {"Gasmessgerät"},
    "gedoresatz": {"Gedore Satz"},
    "generator8kva": {"Generator 8 kVA"},
    "generator9kva": {"Generator 9 kVA"},
    "gerustf.faltbehalter": {"Gerüst f. Faltbehälter"},
    "gerustklammern": {"Gerüstklammern"},
    "gerustklammernverzinkt": {"Gerüstklammern verzinkt"},
    "gerustklemme": {"Gerüstklemme"},
    "glasmanagementset": {"Glasmanagement Set"},
    "grabenstutze": {"Grabenstütze"},
    "greifzug": {"Greifzug"},
    "greifzug30kn": {"Greifzug 30 kN"},
    "greifzughit/32": {"Greifzug HIT/32"},
    "greifzugseil": {"Greifzugseil"},
    "greifzugt35": {"Greifzug T35"},
    "grippplattengreifer": {"Gripp Plattengreifer"},
    "gummihammer": {"Gummihammer"},
    "gummistiefelm.stiefelsocken": {"Gummistiefel m. Stiefelsocken"},
    "gurtf.radklammer": {"Gurt f. Radklammer"},
    "gurtschlauchhalter": {"Gurtschlauchhalter"},
    "hacke": {"Hacke"},
    "hackekurz": {"Hacke kurz"},
    "hackekurzstielig": {"Hacke kurzstielig"},
    "hackelang": {"Hacke lang"},
    "hackelangstielig": {"Hacke langstielig"},
    "hakenelementf.takler": {"Hakenelement f. Takler"},
    "hakenf.kran": {"Haken f. Kran"},
    "hakenleiter": {"Hakenleiter"},
    "hakenm.ose2t": {"Haken m. Öse 2 t"},
    "halligantool": {"Halligan Tool", "Halligantool"},
    "halteseil": {"Halteseil"},
    "hammer2kg": {"Hammer 2 kg"},
    "hammer5kg": {"Hammer 5 kg"},
    "hammerfunkenfrei": {"Hammer funkenfrei"},
    "handbeil": {"Handbeil"},
    "handfasspumpe": {"Handfasspumpe"},
    "handfaustel2kg": {"Handfäustel 2 kg"},
    "handfunkgerat": {"Handfunkgerät"},
    "handfunkterat": {"Handfunkterät"},
    "handhackekurz": {"Handhacke kurz"},
    "handhackelang": {"Handhacke lang"},
    "handhammer": {"Handhammer"},
    "handhammer2kg": {"Handhammer 2 kg"},
    "handlampe": {"Handlampe"},
    "handlampeadalit": {"Handlampe Adalit"},
    "handluftpumpe": {"Handluftpumpe"},
    "handpumpe": {"Handpumpe"},
    "handscheinwerfer": {"Handscheinwerfer"},
    'handscheinwerferwarnlichthaube"orange"': {
        'Handscheinwerfer Warnlichthaube "orange"'
    },
    "handtrennschleifer": {"Handtrennschleifer"},
    "handtuch": {"Handtuch"},
    "haue": {"Haue"},
    "hddruckschlauch15m": {"HD Druckschlauch 15 m"},
    "hdkupplungsschlussel": {"HD Kupplungsschlüssel", "HD-Kupplungsschlüssel"},
    "hdpistolenstrahlrohr": {"HD Pistolenstrahlrohr"},
    "hdrohr": {"HD-Rohr"},
    "hdschlauch60m": {"HD Schlauch 60 m"},
    "hdstrahlrohr": {"HD-Strahlrohr"},
    "hebebaum": {"Hebebaum"},
    "hebegurt4m": {"Hebegurt 4 m"},
    "hebegurt6m": {"Hebegurt 6 m"},
    "hebekissensatz8bar": {"Hebekissensatz 8 bar"},
    "hebekissensatzgross": {"Hebekissen Satz groß"},
    "hebekissensatzklein": {"Hebekissen Satz klein"},
    "helmlampe": {"Helmlampe"},
    "helmmitfunkgarnitur": {"Helm mit Funkgarnitur"},
    "heugabel": {"Heugabel"},
    "heumessgerat": {"Heumessgerät"},
    "heumessgeratanzeige": {"Heumessgerät-Anzeige"},
    "heumesssonde/heumesssonde": {"Heumesssonde / Heumesssonde"},
    "hinweiszettellift": {"Hinweiszettel Lift"},
    "hitzeschutzanzug": {"Hitzeschutzanzug"},
    "hitzeschutzhandschuhe": {"Hitzeschutzhandschuhe"},
    "hitzeschutzhaube": {"Hitzeschutzhaube"},
    "hochdruckhaspelm.pistole": {"Hochdruckhaspel m. Pistole"},
    "hochsichtbareuberwurfweste": {"Hochsichtbare Überwurfweste"},
    "hohlschaufel": {"Hohlschaufel"},
    "hohlstrahlrohr": {"Hohlstrahlrohr"},
    "holzhammer": {"Holzhammer"},
    "holzkeil": {"Holzkeil"},
    "holzpfropfen": {"Holzpfropfen"},
    "homelitepumpe": {"Homelite-Pumpe"},
    "hubwinde": {"Hubwinde"},
    "hubwinde100kn": {"Hubwinde 100 kN"},
    "hydrantenschlussel": {"Hydrantenschlüssel"},
    "hydrantenschlusseloberflur": {"Hydrantenschlüssel Oberflur"},
    "hydraulikverlangerung10m": {"Hydraulikverlängerung 10 m"},
    "hydraulischerrettungssatz": {"Hydraulischer Rettungssatz"},
    "hydraulischerspreizer": {"Hydraulischer Spreizer"},
    "hydraulischeschere": {"Hydraulische Schere"},
    "hydraulischeskompaktaggregat": {"Hydraulisches Kompaktaggregat"},
    "hydrofix": {"Hydrofix"},
    "hydrofix10l": {"Hydrofix 10l"},
    "hydroschildb": {"Hydroschild B"},
    "hydroschildc": {"Hydroschild C"},
    'information"gefahrlichestoffe"': {'Information "Gefährliche Stoffe"'},
    "kabelbedienunglichtmast": {"Kabelbedienung Lichtmast"},
    "kabelbinder": {"Kabelbinder"},
    "kabelfernbedienunglichtmast": {"Kabelfernbedienung Lichtmast"},
    "kabeltrommel230/400v": {"Kabeltrommel 230/400 V"},
    "kabeltrommel230v": {"Kabeltrommel 230 V"},
    "kabeltrommel400v": {"Kabeltrommel 400 V"},
    "kaminkehrerwerkzeug": {"Kaminkehrerwerkzeug", "Kaminkehrer Werkzeug"},
    "kaminkehrwerkzeug": {"Kaminkehrwerkzeug"},
    "kaminschlussel": {"Kaminschlüssel"},
    "kanalabdeckung": {"Kanalabdeckung"},
    "kanalspulratte": {"Kanalspülratte"},
    "kanister": {"Kanister"},
    "kanisterbenzin10l": {"Kanister Benzin 10 l"},
    "kanisterdiesel10l": {"Kanister Diesel 10 l"},
    "kanisterleer10l": {"Kanister leer 10 l"},
    "kantenreiter": {"Kantenreiter"},
    "kantholz": {"Kantholz"},
    "kartentasche": {"Kartentasche"},
    "keil": {"Keil"},
    "kescher": {"Kescher"},
    "ketteeinstrangig67kn": {"Kette einsträngig 67 kN"},
    "kettengehange": {"Kettengehänge"},
    "kettengehange19kn": {"Kettengehänge 19 kN"},
    "kettengehange40kn": {"Kettengehänge 40 kN"},
    "kettengehange56kn": {"Kettengehänge 56 kN"},
    "kettengehange67kn": {"Kettengehänge 67 kN"},
    "kettenstrang10t3m": {"Kettenstrang 10 t 3 m"},
    "kettenstrang15t0,75m": {"Kettenstrang 15 t 0,75 m"},
    "kettenstrang5t5m": {"Kettenstrang 5 t 5 m"},
    "kettenstrang8t3m": {"Kettenstrang 8 t 3 m"},
    "kettezweistrangig56kn": {"Kette zweisträngig 56 kN"},
    "kfzbordwerkzeug": {"KFZ Bordwerkzeug"},
    "kfzstarthilfekabel": {"KFZ Starthilfekabel"},
    "kfzunterlegkeile": {"KFZ Unterlegkeile"},
    "kfzwarndreieck": {"KFZ-Warndreieck"},
    "kfzwerkzeug": {"KFZ Werkzeug"},
    "kippstange": {"Kippstange"},
    "klappkolben60kn": {"Klappkolben 60 kN"},
    "klappspaten": {"Klappspaten"},
    "klebeband": {"Klebeband"},
    "kofferabschlepposen": {"Koffer Abschleppösen"},
    "kohlendioxidloscher5kg": {"Kohlendioxidlöscher 5 kg"},
    "kohlendioxydloscher6kg": {"Kohlendioxydlöscher 6kg"},
    "kombikanister": {"Kombikanister"},
    "kombikanisterf.motorsage": {"Kombikanister f. Motorsäge"},
    "kombikanistermotorsage5l": {"Kombikanister Motorsäge 5 l"},
    "kombileiter": {"Kombileiter"},
    "kombisage/lochsage": {"Kombisäge/Lochsäge"},
    "kombischaumrohrk2": {"Kombischaumrohr K2"},
    "korbtrage": {"Korbtrage"},
    "kraftstoffkanister": {"Kraftstoffkanister"},
    "kraftstoffkanisterf.stromerz.": {"Kraftstoffkanister f. Stromerz."},
    "krampen": {"Krampen"},
    "kranabstutzunterlagen": {"Kranabstützunterlagen"},
    "krankentrage": {"Krankentrage"},
    "krankentrage2teilig": {"Krankentrage 2-teilig"},
    "kransteuergerat": {"Kransteuergerät"},
    "ksa20": {"KSA 20"},
    "ksa20m.stromverteiler": {"KSA 20 m. Stromverteiler"},
    "kuhlbox": {"Kühlbox"},
    "kunststoffeimer": {"Kunststoffeimer"},
    "kunststofffolie": {"Kunststofffolie"},
    "kunststofffolie4x4m": {"Kunststofffolie 4 x 4 m"},
    "kunststoffplanen4x4m": {"Kunststoffplanen 4x4m"},
    "kunststoffsack": {"Kunststoffsack"},
    "kupplungsschlussel": {"Kupplungsschlüssel"},
    "kupplungsschlussel125": {"Kupplungsschlüssel 125"},
    "kupplungsschlusselabc": {"Kupplungsschlüssel ABC"},
    "kupplungsschlusselbc": {"Kupplungsschlüssel B-C"},
    "kurbelf.hydraulikhaspel": {"Kurbel f. Hydraulikhaspel"},
    "ladekabel10m": {"Ladekabel 10 m"},
    "leckdichtkissen": {"Leckdichtkissen"},
    "leckdichtpaste": {"Leckdichtpaste"},
    "lederhandschuhe": {"Lederhandschuhe"},
    "ledschweinwerfer": {"LED-Schweinwerfer"},
    "leichensack": {"Leichensack"},
    "leichtklappklobe": {"Leichtklappklobe"},
    "leinensatz": {"Leinensatz"},
    "lichtfluter": {"Lichtfluter"},
    "lichtfluter1000w": {"Lichtfluter 1000 W"},
    "lichtmastbetatigung": {"Lichtmastbetätigung"},
    "lichtmaststeuerung": {"Lichtmaststeuerung"},
    "loschanlage": {"Löschanlage"},
    "loschdecke": {"Löschdecke"},
    "loschdeckeinkl.beutel": {"Löschdecke inkl. Beutel"},
    "loschlanze": {"Löschlanze"},
    "loschrucksackwaldbrand": {"Löschrucksack Waldbrand"},
    "luftdruckprufer": {"Luftdruckprüfer"},
    "luftschlauchm.luftpistole": {"Luftschlauch m. Luftpistole"},
    "luftschnellangriff20m": {"Luftschnellangriff 20m"},
    "markierleuchtenset": {"Markierleuchtenset"},
    "masken/filterzellstofffabrik": {"Masken/Filter Zellstofffabrik"},
    "mehrbereichsschaummittel": {"Mehrbereichsschaummittel"},
    "mehrzweckleiter": {"Mehrzweckleiter"},
    "mehrzweckstrahlrohrb": {"Mehrzweckstrahlrohr B"},
    "meldertasche": {"Meldertasche"},
    "meldertaschem.zubehor": {"Meldertasche m. Zubehör"},
    "metallbrandpulverloscher": {"Metallbrand Pulverlöscher"},
    "minihebekissensatz": {"Minihebekissensatz"},
    "mistgabel": {"Mistgabel"},
    "mittelschaumpistole": {"Mittelschaumpistole"},
    "monsunrohr": {"Monsunrohr"},
    "moosgummiplatte": {"Moosgummiplatte"},
    "motorkettensage": {"Motorkettensäge"},
    "motorkettensagekurz": {"Motorkettensäge kurz"},
    "motorkettensagelang": {"Motorkettensäge lang"},
    "motorsage": {"Motorsäge"},
    "motorseilwinde": {"Motorseilwinde"},
    "motortrennschleifer": {"Motortrennschleifer"},
    "mullsack": {"Müllsack"},
    "mullsacke": {"Müllsäcke"},
    "nagel": {"Nägel"},
    "nageleisen": {"Nageleisen"},
    "natokabel": {"NATO-Kabel"},
    "netzmittel": {"Netzmittel"},
    "notfalltank": {"Notfalltank"},
    "notfallwanne": {"Notfallwanne"},
    "nothammer": {"Nothammer"},
    "notkurbelf.haspel": {"Notkurbel f. Haspel"},
    "notkurbelfurschlauchhaspel": {"Notkurbel für Schlauchhaspel"},
    "notkurbelhdhaspel": {"Notkurbel HD-Haspel"},
    "notrettungsset": {"Notrettungsset"},
    "notstromkabelf.schere/spreizer": {"Notstromkabel f. Schere/Spreizer"},
    "nusslergefahrguthelfer": {"Nüssler Gefahrguthelfer"},
    "olauffangplane5,5x5,5m": {"Öl-Auffangplane 5,5 x 5,5 m"},
    "olbindemittel": {"Ölbindemittel"},
    "olbindemittelkanister": {"Ölbindemittelkanister"},
    "olbindemittelreservesack": {"Ölbindemittel Reservesack"},
    "olkanister": {"Ölkanister"},
    "olschlange": {"Ölschlange"},
    "pannendreieck": {"Pannendreieck"},
    "paxmeldertasche": {"PAX-Meldertasche"},
    "pedalschneider": {"Pedalschneider"},
    "peplane4x4m": {"PE-Plane 4 x 4 m"},
    "personensicherungsset": {"Personen-Sicherungsset"},
    "piasavabesen": {"Piasavabesen", "Piasava Besen"},
    "piassavabesen": {"Piassava-Besen"},
    "plane1,4x2,2m": {"Plane 1,4 x 2,2 m"},
    "plane3x4m": {"Plane 3 x 4 m"},
    "plane4x4m": {"Plane 4 x 4 m"},
    "plastikfolie": {"Plastikfolie"},
    "prazisionszumischer": {"Präzisionszumischer"},
    "pressluftatmer": {"Pressluftatmer"},
    "pressluftschlauche": {"Pressluftschläuche"},
    "pressluftschlauchgerat": {"Pressluftschlauchgerät"},
    "pulverloscherabc12kg": {"Pulverlöscher ABC 12 kg"},
    "pvceinfulltrichter": {"PVC Einfülltrichter"},
    "pvcfolie": {"PVC-Folie"},
    "radkeil": {"Radkeil"},
    "radklammer": {"Radklammer"},
    "radkreuzf.lkw": {"Radkreuz f. LKW"},
    "radkreuzf.pkw": {"Radkreuz f. PKW"},
    "randschaufel": {"Randschaufel"},
    "rangierrollerlenkbar": {"Rangierroller lenkbar"},
    "rangierwagenheber1,5t": {"Rangierwagenheber 1,5 t"},
    "ratschnesatz": {"Ratschnesatz"},
    "rauchabschluss": {"Rauchabschluss"},
    "rauchfangschlusselsatz": {"Rauchfangschlüsselsatz"},
    "rauchfangturschlussel": {"Rauchfangtürschlüssel"},
    "rauchvorhang": {"Rauchvorhang"},
    "reifenfullschlauch": {"Reifenfüllschlauch"},
    "reserveakkuf.akkugerate": {"Reserveakku f. Akkugeräte"},
    "reserveflasche": {"Reserveflasche"},
    "reservekettef.motorsage": {"Reservekette f. Motorsäge"},
    "reservemaske": {"Reservemaske"},
    "respihood": {"Respihood"},
    "rettungsdecke": {"Rettungsdecke"},
    "rettungsleine": {"Rettungsleine"},
    "rettungsleine30m": {"Rettungsleine 30 m"},
    "rettungsplattform": {"Rettungsplattform"},
    "rettungsring": {"Rettungsring"},
    "rettungssage": {"Rettungssäge"},
    "rettungssagestihl": {"Rettungssäge Stihl"},
    "rettungswerkzeug": {"Rettungswerkzeug"},
    "risbeleuchtungssystem": {"RIS-Beleuchtungssystem"},
    "robisrohrm.schlauch": {"Robisrohr m. Schlauch"},
    "rohrdichtkissen": {"Rohrdichtkissen"},
    "rohrkrummer": {"Rohrkrümmer"},
    "rohrzange": {"Rohrzange"},
    "rohrzangefunkenfrei": {"Rohrzange funkenfrei"},
    "rollemullsacke": {"Rolle Müllsäcke"},
    "rollgliss": {"Rollgliss"},
    "rollglissbugel": {"Rollgliss Bügel"},
    "rollglissmitabseilachter": {"Rollgliss mit Abseilachter"},
    "rundschaufel": {"Rundschaufel"},
    "rundschlinge": {"Rundschlinge"},
    "rundschlinge40kn": {"Rundschlinge 40 kN"},
    "rundschlinge60kn": {"Rundschlinge 60 kN"},
    "rustholz": {"Rüstholz"},
    "sabelsage": {"Säbelsäge"},
    "sabelsageakku": {"Säbelsäge Akku"},
    "safetypeakbugel": {"Safety Peak Bügel"},
    "saftypeak": {"Safty Peak"},
    "sammelstuck": {"Sammelstück"},
    "sammelstuck2ba": {"Sammelstück 2B-A"},
    "sammelstucka2b": {"Sammelstück A - 2B"},
    "sammelstuckabb": {"Sammelstück A-BB"},
    "sammelstuckbba": {"Sammelstück BB-A"},
    "sammelstuckbbba": {"Sammelstück BBB-A"},
    "sanitatskasten": {"Sanitätskasten"},
    "sanitatskastenm.beatmungsbeutel": {"Sanitätskasten m. Beatmungsbeutel"},
    "sanitatsrucksack": {"Sanitätsrucksack"},
    "sappie": {"Sappie"},
    "sappine": {"Sappine"},
    "satzschlauchbinden": {"Satz Schlauchbinden"},
    "sauerstoffselbstretter": {"Sauerstoff-Selbstretter"},
    "saugkopfb": {"Saugkopf B"},
    "saugkorb": {"Saugkorb"},
    "saugschlaucha": {"Saugschlauch A"},
    "saugschlauchb": {"Saugschlauch B"},
    "saugschlauchd": {"Saugschlauch D"},
    "saugschlauchdf.zumischer": {"Saugschlauch D f. Zumischer"},
    "saureschutzhandschuhe": {"Säureschutzhandschuhe"},
    "schachtabdeckung": {"Schachtabdeckung"},
    "schachthaken": {"Schachthaken"},
    "schachthakensatz": {"Schachthakensatz"},
    "schackel": {"Schäckel"},
    "schackel65kn": {"Schäckel 65 kN"},
    "schakel": {"Schäkel"},
    "schakel10t": {"Schäkel 10 t"},
    "schakel120kn": {"Schäkel 120 kN"},
    "schakel12t": {"Schäkel 12 t"},
    "schakel15t": {"Schäkel 15 t"},
    "schakel5t": {"Schäkel 5 t"},
    "schakel6,5t": {"Schäkel 6,5 t"},
    "schakel65kn": {"Schäkel 65 kN"},
    "schakel6t": {"Schäkel 6 t"},
    "schaufel": {"Schaufel"},
    "schaufeltrage": {"Schaufeltrage"},
    "schaumaufsatzf.wasserwerfer": {"Schaumaufsatz f. Wasserwerfer"},
    "schaumaufsatzfurpistolenstrahlrohr": {"Schaumaufsatz für Pistolenstrahlrohr"},
    "schaumausrustung": {"Schaumausrüstung"},
    "schaumgummimatte": {"Schaumgummimatte"},
    "schaummittel": {"Schaummittel"},
    "schaummittelkanister": {"Schaummittelkanister"},
    "schaumpumpenvormischer": {"Schaum-Pumpenvormischer"},
    "schaumrohr": {"Schaumrohr"},
    "scheinwerfer1500w": {"Scheinwerfer 1500 W"},
    "scheinwerferbrucke": {"Scheinwerferbrücke"},
    "schiebeleiter": {"Schiebeleiter"},
    "schiebeleiter2teilig": {"Schiebeleiter 2-teilig"},
    "schiebeleiter2teilig8m": {"Schiebeleiter 2-teilig 8 m"},
    "schiebeleiter3teilig": {"Schiebeleiter 3-teilig"},
    "schlagbohrmaschine": {"Schlagbohrmaschine"},
    "schlagbohrmaschinemitbohrersatz": {"Schlagbohrmaschine mit Bohrersatz"},
    "schlauchbindeb75": {"Schlauchbinde B75"},
    "schlauchbindec52": {"Schlauchbinde C52"},
    "schlauchbinden": {"Schlauchbinden"},
    "schlauchbindensatz": {"Schlauchbindensatz"},
    "schlauchbrucke": {"Schlauchbrücke"},
    "schlauchbrucken": {"Schlauchbrücken"},
    "schlauchbruckepaaralu": {"Schlauchbrücke Paar Alu"},
    "schlauchf.schaumaufsatzwasserwerfer": {"Schlauch f. Schaumaufsatz Wasserwerfer"},
    "schlauchhalter": {"Schlauchhalter"},
    "schlauchhaspel": {"Schlauchhaspel"},
    "schlauchknickschutz": {"Schlauchknickschutz"},
    "schlauchladenb": {"Schlauchladen B"},
    "schlauchpaket": {"Schlauchpaket"},
    "schlauchrollwagen": {"Schlauchrollwagen"},
    "schlauchtragekorb": {"Schlauchtragekorb"},
    "schlauchtrager": {"Schlauchträger"},
    "schleiferbrille": {"Schleiferbrille"},
    "schleifkorbtrage": {"Schleifkorbtrage"},
    "schleifkorbtragem.gehange": {"Schleifkorbtrage m. Gehänge"},
    "schleifringkabeltrommel": {"Schleifringkabeltrommel"},
    "schleifringtrommel400v": {"Schleifringtrommel 400 V"},
    "schlusself.hauswasserabsperrung": {"Schlüssel f. Hauswasserabsperrung"},
    "schlusself.trennschleifer": {"Schlüssel f. Trennschleifer"},
    "schlusselkasten": {"Schlüsselkasten"},
    "schlusselset": {"Schlüsselset"},
    "schlusselsortiment": {"Schlüsselsortiment"},
    "schmutzwasserpumpe": {"Schmutzwasserpumpe"},
    "schneekette": {"Schneekette"},
    "schneeketten": {"Schneeketten"},
    "schnellangriffkabeltrommelm.verteiler": {
        "Schnellangriff Kabeltrommel m. Verteiler"
    },
    "schnellinfogefahrenstoffe": {"Schnellinfo Gefahrenstoffe"},
    "schnittschutzbeinlinge": {"Schnittschutzbeinlinge"},
    "schnittschutzhelm": {"Schnittschutzhelm"},
    "schnittschutzhose": {"Schnittschutzhose"},
    "schnittschutzjacke": {"Schnittschutzjacke"},
    "schnurleine": {"Schnürleine"},
    "schnurleine6m": {"Schnürleine 6 m"},
    "schreibmaterial": {"Schreibmaterial"},
    "schuttwanne": {"Schuttwanne"},
    "schutzanzug": {"Schutzanzug"},
    "schutzanzugschutzstufe2": {"Schutzanzug Schutzstufe 2"},
    "schutzanzugunterbekleidung": {"Schutzanzug Unterbekleidung"},
    "schutzbrille": {"Schutzbrille"},
    "schutzdecke": {"Schutzdecke"},
    "schutzdeckenset": {"Schutzdeckenset"},
    "schutzhandschuhe": {"Schutzhandschuhe"},
    "schutzkorbf.saugkorb": {"Schutzkorb f. Saugkorb"},
    "schwellenaufsatz": {"Schwellenaufsatz"},
    "schwelleraufsatz": {"Schwelleraufsatz"},
    "schwerlastaufnahme": {"Schwerlastaufnahme"},
    "schwimmsauger": {"Schwimmsauger"},
    "segeltuchbeutelf.schlauchbinden": {"Segeltuchbeutel f. Schlauchbinden"},
    "segeltucheimer": {"Segeltucheimer"},
    "seilf.greifzug": {"Seil f. Greifzug"},
    "seilfuhrungsrollef.kranseilwinde": {"Seilführungsrolle f. Kranseilwinde"},
    "seilkeilgross": {"Seilkeil groß"},
    "seilkeilklein": {"Seilkeil klein"},
    "seilklemme": {"Seilklemme"},
    "seilrolle60kn": {"Seilrolle 60 kN"},
    "seilschlinge16mm20m": {"Seilschlinge 16 mm 20 m"},
    "seilschlinge25mm3m": {"Seilschlinge 25 mm 3 m"},
    "seilstropp10m": {"Seilstropp 10 m"},
    "seilstropp2,5m": {"Seilstropp 2,5 m"},
    "seilstropp5m": {"Seilstropp 5 m"},
    "seilstroppverz.": {"Seilstropp verz."},
    "selbstschweissendesdichtband": {"Selbstschweißendes Dichtband"},
    "setpowerflares": {"Set Powerflares"},
    "sicherheitsgeschirr": {"Sicherheitsgeschirr"},
    "sicherheitshandschuhe": {"Sicherheitshandschuhe"},
    "sicherungsgeschirr": {"Sicherungsgeschirr"},
    "sicherungsleine2m": {"Sicherungsleine 2m"},
    "sichtschutz": {"Sichtschutz"},
    "signaltaschenlampe": {"Signaltaschenlampe"},
    "sitzgurtrettungsgeschirr": {"Sitzgurt-Rettungsgeschirr"},
    "spannringfass60l": {"Spannringfass 60 l"},
    "spaten": {"Spaten"},
    "spezialhebematte2,5t": {"Spezial Hebematte 2,5 t"},
    "spillbag15": {"Spillbag 15"},
    "spilltecholabsorbent1,2m": {"Spilltech Öl-Absorbent 1,2 m"},
    "spinboard": {"Spinboard"},
    "spiralluton": {"Spiralluton"},
    "spitzschaufel": {"Spitzschaufel"},
    "spitzschneidekrampen": {"Spitzschneidekrampen"},
    "spitzschneidekrampen2,5kg": {"Spitzschneidekrampen 2,5 kg"},
    "sprungpolster": {"Sprungpolster"},
    "stabfast": {"Stabfast"},
    "stabpacks": {"StabPacks"},
    "stahlblecheimer": {"Stahlblecheimer"},
    "stahlseil5m": {"Stahlseil 5 m"},
    "stahlseilstropp2,5m": {"Stahlseilstropp 2,5 m"},
    "stahlseilstropp5m": {"Stahlseilstropp 5 m"},
    "standrohr": {"Standrohr"},
    "stangef.rangierwagenheber": {"Stange f. Rangierwagenheber"},
    "starterkabel": {"Starterkabel"},
    "starthilfekabel": {"Starthilfekabel"},
    "stativ": {"Stativ"},
    "stativ1,7m": {"Stativ 1,7 m"},
    "stativ5m": {"Stativ 5 m"},
    "staubmaske": {"Staubmaske"},
    "steckleiter": {"Steckleiter"},
    "steckleiter4teilig": {"Steckleiter 4-teilig"},
    "steckleiterverbindungsteil": {"Steckleiter Verbindungsteil"},
    "steckschlusselsatz": {"Steckschlüsselsatz"},
    "steigergurt": {"Steigergurt"},
    "steuerungseilwinde": {"Steuerung Seilwinde"},
    "stichschaufel": {"Stichschaufel"},
    "stockschlusselsatz": {"Stockschlüsselsatz"},
    "strahlrohrb": {"Strahlrohr B"},
    "strahlrohrbm.stutzkrummer": {"Strahlrohr B m. Stützkrümmer"},
    "strassenbesen": {"Straßenbesen"},
    "streuwagen": {"Streuwagen"},
    "strickleiter20m": {"Strickleiter 20 m"},
    "stromerzeuger": {"Stromerzeuger"},
    "stromerzeuger10kva": {"Stromerzeuger 10 kVA"},
    "stromerzeuger14kva": {"Stromerzeuger 14 kVA"},
    "stromerzeuger30kva": {"Stromerzeuger 30 kVA"},
    "stromerzeugerklein": {"Stromerzeuger klein"},
    "stromerzeugermag": {"Stromerzeuger MAG"},
    "stromgenerator": {"Stromgenerator"},
    "stromschnellangriff": {"Stromschnellangriff"},
    "stromverteiler": {"Stromverteiler"},
    "sturmleine": {"Sturmleine"},
    "stutzkrummer": {"Stützkrümmer"},
    "stutzkrummerb": {"Stützkrümmer B"},
    "stutzstange": {"Stützstange"},
    "suchscheinwerfer": {"Suchscheinwerfer"},
    "suchstock": {"Suchstock"},
    "sudbahnwinde": {"Südbahnwinde"},
    "tablet": {"Tablet"},
    'tafel"olspur"': {'Tafel "Ölspur"'},
    "tauchpumpe": {"Tauchpumpe"},
    "tauchpumpe230v": {"Tauchpumpe 230 V"},
    "tauchpumpe2400l/min": {"Tauchpumpe 2400 l/min"},
    "tauchpumpe850l/min": {"Tauchpumpe 850 l/min"},
    "teleskopleiter": {"Teleskopleiter"},
    "teleskopleiter3,5m": {"Teleskopleiter 3,5 m"},
    "teleskoprettunszylinder": {"Teleskoprettunszylinder"},
    "tnttool": {"TNT-Tool", "TNT Tool"},
    "totmannwarner": {"Totmannwarner"},
    "tragbarerwasserwerfer": {"Tragbarer Wasserwerfer"},
    "tragerklemme5t": {"Trägerklemme 5 t"},
    "tragetuch": {"Tragetuch"},
    "tragkraftspritze": {"Tragkraftspritze"},
    "trainingsanzug": {"Trainingsanzug"},
    "trassenband": {"Trassenband"},
    "treibstoffolkanister": {"Treibstoff-Ölkanister"},
    "trennschleifer": {"Trennschleifer"},
    "trichter": {"Trichter"},
    "triopanfeuerwehr": {"Triopan FEUERWEHR"},
    "trockenloscher12kg": {"Trockenlöscher 12 kg"},
    "turbrecheisen": {"Türbrecheisen"},
    "turbrecheisen/schaleisen": {"Türbrecheisen/Schaleisen"},
    "turoffner": {"Türöffner"},
    "turoffnungskoffer": {"Türöffnungskoffer"},
    "turoffnungsset": {"Türöffnungsset"},
    "uberdruckentlufter": {"Überdruckentlüfter"},
    "uberflurhydrantenschlussel": {"Überflurhydrantenschlüssel"},
    "uberflurhydrantenschlusselm.ratsche": {"Überflurhydrantenschlüssel m. Ratsche"},
    "ubergangsstuck110125": {"Übergangsstück 110-125"},
    "ubergangsstuck125110": {"Übergangsstück 125-110"},
    "ubergangsstuck400v": {"Übergangsstück 400 V"},
    "ubergangsstuck400vm.polwender": {"Übergangsstück 400 V m. Polwender"},
    "ubergangsstuck400vmitpolwender": {"Übergangsstück 400 V mit Polwender"},
    "ubergangsstucka/b": {"Übergangsstück A/B"},
    "ubergangsstucka110b75": {"Übergangsstück A110-B75"},
    "ubergangsstucka125/110": {"Übergangsstück A 125/110"},
    "ubergangsstucka125a": {"Übergangsstück A125-A"},
    "ubergangsstucka125a110": {"Übergangsstück A125-A110"},
    "ubergangsstuckaa125": {"Übergangsstück A-A125"},
    "ubergangsstuckab": {"Übergangsstück A-B"},
    "ubergangsstuckb/c": {"Übergangsstück B/C"},
    "ubergangsstuckb75c52": {"Übergangsstück B75-C52"},
    "ubergangsstuckbc": {"Übergangsstück B-C"},
    "ubergnagsstuckab": {"Übergnagsstück A-B"},
    "ubergnagsstuckbc": {"Übergnagsstück B-C"},
    "umlenkrolle100kn": {"Umlenkrolle 100 kN"},
    "umlenkrolle140kn": {"Umlenkrolle 140 kN"},
    "umlenkrolle200kn": {"Umlenkrolle 200 kN"},
    "umlenkrollef.kranseilwinde": {"Umlenkrolle f. Kranseilwinde"},
    "universalolbindemittel": {"Universal Ölbindemittel"},
    "unterbauschiebeblock": {"Unterbauschiebeblock"},
    "unterflurhydrantenschlussel": {
        "Unterflur-Hydrantenschlüssel",
        "Unterflurhydrantenschlüssel",
    },
    "unterflurhydrantenstandrohr": {"Unterflur-Hydrantenstandrohr"},
    "unterlegholzer": {"Unterleghölzer"},
    "unterlegkeil": {"Unterlegkeil"},
    "unterlegkeilseilwinde": {"Unterlegkeil Seilwinde"},
    "unterlegmattengummi": {"Unterlegmatten Gummi"},
    "unterlegrollen": {"Unterlegrollen"},
    "unterlegsholz": {"Unterlegsholz"},
    "unterschiebbock": {"Unterschiebbock"},
    "ventilhalteleine": {"Ventilhalteleine"},
    "verbandskaste": {"Verbandskaste"},
    "verbandskasten": {"Verbandskasten"},
    "verbindungsmittel15vario": {"Verbindungsmittel 15 Vario"},
    "verbindungsschlauchb": {"Verbindungsschlauch B"},
    "verbindungsschlauchb5m": {"Verbindungsschlauch B 5m"},
    "verbindungsschlauchhebekissen": {"Verbindungsschlauch Hebekissen"},
    "verbindungsschlauchleckdichtkissen": {"Verbindungsschlauch Leckdichtkissen"},
    "verbundglasschneider": {"Verbundglasschneider"},
    "verkehrsleitkegel": {"Verkehrsleitkegel"},
    "verkehrsleitkegelfaltbar": {"Verkehrsleitkegel faltbar"},
    "verkehrsunfallschnellangriffskoffer": {"Verkehrsunfall- Schnellangriffskoffer"},
    "verlangerungskabel": {"Verlängerungskabel"},
    "verlangerungskabel10m": {"Verlängerungskabel 10 m"},
    "verlangerungskabel230v": {"Verlängerungskabel 230 V"},
    "verlangerungskabel230v10m": {"Verlängerungskabel 230 V 10 m"},
    "verlangerungskabel400v": {"Verlängerungskabel 400 V"},
    "verteilerbcbc": {"Verteiler B-CBC"},
    "verteilercbc": {"Verteiler CBC"},
    "verteilerkabeltrommel230v30m": {"Verteilerkabeltrommel 230 V 30 m"},
    "verteilerkabeltrommel30m400v": {"Verteilerkabeltrommel 30 m 400 V"},
    "verzurreinrichtung": {"Verzurreinrichtung"},
    "verzurreinrichtungf.stativ": {"Verzurreinrichtung f. Stativ"},
    "vollmaskef.pressluftatmer": {"Vollmaske f. Pressluftatmer"},
    "vorschlaghammer": {"Vorschlaghammer"},
    "vorschlaghammer5kg": {"Vorschlaghammer 5 kg"},
    "wagenheber": {"Wagenheber"},
    "wagenheber10t": {"Wagenheber 10 t"},
    "waldbrandrucksack": {"Waldbrandrucksack"},
    "warmebildkamera": {"Wärmebildkamera"},
    "warnblitzleuchte": {"Warnblitzleuchte"},
    'warndreieck"feuerwehr"': {'Warndreieck "Feuerwehr"'},
    'warndreieck"oleinsatz"': {'Warndreieck "Öleinsatz"'},
    'warnlichthaube"orange"': {'Warnlichthaube "orange"'},
    "warnlichthaubef.handscheinwerfer": {"Warnlichthaube f. Handscheinwerfer"},
    "warnlichthaubenfurhandscheinwerfer": {"Warnlichthauben für Handscheinwerfer"},
    "warntafel": {"Warntafel"},
    "warnuberwurf": {"Warnüberwurf"},
    "warnuberwurfeinsatzleiter": {"Warnüberwurf Einsatzleiter"},
    'warnzeichen"feuerwehr"': {'Warnzeichen "Feuerwehr"'},
    "wassersaugerm.zubehor": {"Wassersauger m. Zubehör"},
    "wasserschieber": {"Wasserschieber"},
    "wasserwerfer": {"Wasserwerfer"},
    "wathose": {"Wathose"},
    "wenderohr": {"Wenderohr"},
    "werkzeugf.motorkettensage": {"Werkzeug f. Motorkettensäge"},
    "werkzeugf.ts": {"Werkzeug f. TS"},
    "werkzeugkiste": {"Werkzeugkiste"},
    "werkzeugkoffer": {"Werkzeugkoffer"},
    "werkzeugkofferausstahlblech": {"Werkzeugkoffer aus Stahlblech"},
    "werkzeugsatz": {"Werkzeugsatz"},
    "werkzeugsatzi.trage": {"Werkzeugsatz i. Trage"},
    "werkzeugsatztragkraftspritze": {"Werkzeugsatz Tragkraftspritze"},
    "werkzeugsatzvu": {"Werkzeugsatz VU"},
    "winde10t": {"Winde 10 t"},
    "windenkeil": {"Windenkeil"},
    "windensteuergerat": {"Windensteuergerät"},
    "wirbelhaken": {"Wirbelhaken"},
    "wolldecke": {"Wolldecke"},
    "zimmermannshammer": {"Zimmermannshammer"},
    "zubehorschere/spreizer": {"Zubehör Schere/Spreizer"},
    "zumischer": {"Zumischer"},
    "zumischerz2": {"Zumischer Z2"},
    "zumischerz2/z4": {"Zumischer Z2/Z4"},
    "zurrgurt": {"Zurrgurt"},
    "zurrgurt7m": {"Zurrgurt 7 m"},
    "zurrgurt7m1teilig": {"Zurrgurt 7m 1-teilig"},
    "zurrgurtm.ratsche8m2teilig": {"Zurrgurt m. Ratsche 8m 2-teilig"},
    "zurrgurtmitratsche": {"Zurrgurt mit Ratsche"},
    "zylinderunterlegsgestell": {"Zylinder Unterlegsgestell"},
    "zylinderverlangerung": {"Zylinder Verlängerung"},
}
