def load_total_storage():
    return {
        "Rüst+Lösch": {
            "Fahrer/GK": [
                "Handfunkgerät",
                "Gasmessgerät",
                "Nüssler Gefahrguthelfer",
                "PAX-Meldertasche",
                "Auto-Öffnungswerkzeug",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer"
            ],
            "Mannschaft": [
                "Anhaltekelle",
                "Handfunkgerät",
                "Warndreieck \"Feuerwehr\"",
                "Rettungsleine",
                "FW-Gurt",
                "Notrettungsset",
                "Feuerwehrauffanggurt",
                "Basis Sichern/Auffangen",
                "A2-Sanitätsrucksack",
                "Einweghandschuhe",
                "Alu-Rettungsdecke",
                "Wolldecke",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Reserveflasche",
                "Totmannwarner",
                "Brandfluchthaube",
                "Wärmebildkamera",
                "Schutzhandschuhe",
                "Hochsichtbare Überwurfweste",
                "Handlampe",
                "Respihood",
                "Kühlbox",
                "Tragetuch",
                "Leichensack",
                "Trainingsanzug",
                "Handtuch",
                "Euro-Blitz Leuchte"
            ],
            "G1": [
                "Spinboard",
                "Schnittschutzhose",
                "Arbeitsmesser",
                "Bogensäge",
                "Bolzenschneider",
                "Hacke langstielig",
                "Hacke kurzstielig",
                "Vorschlaghammer 5 kg",
                "Handfäustel 2 kg",
                "Brechstange lang 1,5 m",
                "Feuerwehraxt",
                "Halligantool",
                "Piassava-Besen",
                "Fassschaufel",
                "Aluminium Randschaufel",
                "Krampen",
                "Feuerwehrsappel",
                "Bindedraht verzinkt",
                "Gerüstklammern verzinkt",
                "Nägel",
                "Schachthaken",
                "Drahtseilkemmen",
                "Drahtseil verzinkt 5 m",
                "Drahtseil verzinkt 10 m",
                "Reservekette f. Motorsäge",
                "Rundschlinge 60 kN",
                "Kette einsträngig 67 kN",
                "Kette zweisträngig 56 kN",
                "Schäkel 65 kN",
                "Schäkel 120 kN",
                "Aggregat f. hydr. Rettungssatz",
                "Handpumpe",
                "Hydraulischer Spreizer",
                "Hydraulische Schere",
                "Doppelwirkender Rettungszylinder",
                "Pedalschneider",
                "Akku Kombigerät",
                "Schwellenaufsatz",
                "Werkzeugsatz VU",
                "Schutzdeckenset",
                "Unterbauschiebeblock",
                "Abstützsystem",
                "Freilandverankerung",
                "Greifzug",
                "Greifzugseil",
                "Umlenkrolle 100 kN",
                "Kantenreiter",
                "Umlenkrolle 140 kN",
                "Winde 10 t",
                "Motorsäge",
                "Rettungssäge Stihl",
                "Kombikanister f. Motorsäge",
                "Ersatzkette Rettungssäge",
                "Rauchfangtürschlüssel"
            ],
            "G2": [
                "Schlagbohrmaschine mit Bohrersatz",
                "Europa Absperrband",
                "Absperrständer",
                "Bodenteller f. Absperrständer",
                "Verkehrsleitkegel",
                "Blitzer LED",
                "Erdungsspieß",
                "Erdungszwingen",
                "Erdungsschiene",
                "Erdungslitzen",
                "Lichtfluter",
                "Stativ",
                "Aufnahmebrücke f. Fluter",
                "Stromerzeuger",
                "Abgasschlauch f. Stromerz.",
                "Kraftstoffkanister f. Stromerz.",
                "Einfüllstutzen",
                "Verteilerkabeltrommel 30 m 400 V",
                "Fixeingebaute Kabeltrommel",
                "Kabeltrommel 230 V",
                "Verlängerungskabel",
                "Druckluftflasche f. Hebekissen",
                "Hebekissensatz 8 bar",
                "Druckbelüfter",
                "Kraftstoffkanister",
                "Ausgießstutzen",
                "Markierleuchtenset"
            ],
            "G3": [
                "Türöffnungsset",
                "Schlauchtragekorb",
                "Druckschlauch C",
                "Hohlstrahlrohr",
                "Saugschlauch D f. Zumischer",
                "Schaummittelkanister",
                "Zumischer Z2",
                "Kombischaumrohr K2",
                "Rauchvorhang",
                "Arbeitsleine"
            ],
            "G4": [
                "Werkzeugsatz",
                "Zurrgurt",
                "Schnürleine",
                "Unterlegkeil Seilwinde",
                "Trennschleifer",
                "Säbelsäge Akku",
                "Akku f. Säbelsäge",
                "Schutzbrille",
                "Staubmaske",
                "Doppelmembran Pumpe",
                "Auffangtank 1500 l",
                "Rolle Müllsäcke",
                "Schuttwanne",
                "Auffangplane 3x4 m",
                "Auffangsack Spillpacks",
                "Dichtkeil",
                "Holzhammer",
                "Dichtpfropfen"
            ],
            "G5": [
                "Kupplungsschlüssel ABC",
                "Druckschlauch B",
                "Verbindungsschlauch B",
                "Satz Schlauchbinden",
                "Schlauchhalter",
                "Hohlstrahlrohr",
                "Mehrzweckstrahlrohr B",
                "Stützkrümmer B",
                "Druckbegrenzungsventil B",
                "Verteiler B-CBC",
                "Sammelstück 2B-A",
                "Übergangsstück A-B",
                "Übergangsstück A125-A",
                "Übergangsstück B-C",
                "Überflurhydrantenschlüssel",
                "Hydroschild C",
                "Tauchpumpe",
                "Blindkupplungen f. Ölsperre",
                "Druckschlauch C"
            ],
            "G6": [
                "Schneeketten",
                "Kunststoffeimer",
                "Löschdecke inkl. Beutel",
                "CAFS Löscher 10 l",
                "Trockenlöscher 12 kg",
                "Kohlendioxidlöscher 5 kg",
                "HD-Kupplungsschlüssel",
                "Tragbarer Wasserwerfer",
                "Unterlegsholz",
                "Druckschlauch B"
            ],
            "Heck": [
                "Handfunkgerät",
                "Schlauchhaspel",
                "Atemschutz Überwachungstafel",
                "Abschleppstange"
            ],
            "Dach": [
                "Moosgummiplatte",
                "Schlauchbrücke Paar Alu",
                "Schiebeleiter 3-teilig",
                "Steckleiter 4-teilig",
                "Steckleiter Verbindungsteil",
                "Chemieschutzstiefel",
                "Chemieschutzhandschuhe",
                "Chemieschutzanzug Stufe 2",
                "Ausräumhaken",
                "Heugabel",
                "Einreißhaken",
                "Kescher",
                "Schachtabdeckung"
            ]
        },
        "Tank1": {
            "Fahrer/GK": [
                "Handfunkgerät",
                "Gasmessgerät",
                "Reserveakku f. Akkugeräte",
                "Heumessgerät-Anzeige",
                "Schlüsselset",
                "Hinweiszettel Lift",
                "Dreieck-Schlüssel",
                "Handlampe",
                "FFP2-Mask",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Suchscheinwerfer",
                "Einweghandschuhe"
            ],
            "Mannschaft": [
                "Handfunkgerät",
                "Schutzhandschuhe",
                "Handbeil",
                "Trainingsanzug",
                "Handtuch",
                "Warnzeichen \"Feuerwehr\"",
                "Handscheinwerfer Warnlichthaube \"orange\"",
                "FW-Gurt",
                "Warnüberwurf",
                "Reserveflasche",
                "Ladekabel 10 m",
                "Kippstange",
                "Starterkabel",
                "Filteratemschutz",
                "Reservemaske",
                "Rettungsleine",
                "Wärmebildkamera",
                "Handlampe",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "TNT-Tool",
                "Erste-Hilfe-Koffer",
                "Anhaltekelle",
                "Decke",
                "Tragetuch",
                "Notrettungsset",
                "Fluchthaube"
            ],
            "G1": [
                "Elektrokettensäge",
                "Kombikanister",
                "Forsthelm",
                "Schnittschutzbeinlinge",
                "Motorkettensäge",
                "Rettungssäge",
                "Drucklüfter",
                "Schneeketten",
                "Waldbrandrucksack",
                "Tauchpumpe",
                "Abschleppseil",
                "Stahlseil 5 m",
                "Schäkel",
                "Handfasspumpe",
                "Pressluftschläuche",
                "Pressluftschlauchgerät",
                "Benzinkanister",
                "Dieselkanister"
            ],
            "G2": [
                "Deckelabzieher",
                "Einbruchwerkzeug",
                "Schaufeltrage",
                "Krankentrage",
                "Fluterbrücke",
                "Fluter 1500 W",
                "Schlüssel f. Trennschleifer",
                "Stahlblecheimer",
                "Kunststoffeimer",
                "Schleifringkabeltrommel",
                "Kabeltrommel 230/400 V",
                "Lichtmaststeuerung",
                "Verlängerungskabel",
                "Abgasschlauch",
                "Hacke",
                "Schachthaken",
                "Elektrowerkzeugsatz",
                "Handhammer",
                "Fassschlüssel",
                "Zimmermannshammer",
                "Trichter",
                "Schutzbrille",
                "Staubmaske",
                "Werkzeugkiste",
                "Stockschlüsselsatz",
                "Verzurreinrichtung f. Stativ",
                "Stromerzeuger 14 kVA",
                "Absperrschlüssel f. Gas",
                "Absperrschlüssel f. Hauswasser",
                "Brechstange",
                "Straßenbesen",
                "Bolzenschneider",
                "Feuerwehraxt",
                "Vorschlaghammer",
                "Randschaufel",
                "Hacke lang",
                "Brecheisen",
                "Elektrorettungshaken"
            ],
            "G3": [
                "Schaumrohr",
                "Schaummittel",
                "Netzmittel",
                "Zumischer",
                "Saugschlauch D",
                "Flammschutzbekleidung",
                "Hitzeschutzhaube",
                "Schaum-Pumpenvormischer"
            ],
            "G4": [
                "Verkehrsleitkegel",
                "Bodenteller f. Absperrstangen",
                "Masken/Filter Zellstofffabrik",
                "Fognail",
                "Türöffnungskoffer",
                "Absperrband",
                "Schutzanzug Unterbekleidung",
                "Chemieschutzanzug",
                "Bogensäge",
                "Arbeitsleine",
                "Säureschutzhandschuhe",
                "Schnürleine",
                "Dekowanne",
                "Müllsack",
                "Kanalabdeckung",
                "PE-Plane 4 x 4 m",
                "Kunststofffolie 4 x 4 m",
                "Absperrstangen"
            ],
            "G5": [
                "Druckschlauch B",
                "Druckschlauch C42",
                "Schlauchpaket",
                "Verteiler CBC",
                "Flankierer",
                "Hohlstrahlrohr",
                "Stützkrümmer",
                "Mehrzweckstrahlrohr B",
                "Hydrantenschlüssel",
                "Übergangsstück A-B",
                "Übergangsstück A-A125",
                "ABC-Kupplungsschlüssel",
                "Übergangsstück B-C",
                "Hydroschild C",
                "Druckbegrenzungsventil",
                "Sammelstück",
                "Schlauchtragekorb",
                "Rauchvorhang",
                "Schlauchhalter",
                "Schlauchbinden"
            ],
            "G6": [
                "Löschdecke",
                "Druckschlauch B",
                "Druckschlauch HD",
                "Kaminkehrer Werkzeug",
                "Schlauch f. Schaumaufsatz Wasserwerfer",
                "Wasserwerfer",
                "Schaumaufsatz f. Wasserwerfer",
                "Sammelstück BBB-A",
                "Fettbrandlöscher",
                "ABC-Pulverlöscher",
                "Hydrofix",
                "CO2 Löscher",
                "Metallbrand Pulverlöscher",
                "HD Kupplungsschlüssel",
                "Notkurbel f. Haspel",
                "HD Pistolenstrahlrohr",
                "Fahrzeug Unterlegkeile"
            ],
            "Heck": [
                "Handfunkgerät",
                "ABC-Kupplungsschlüssel",
                "HD-Rohr",
                "Löschlanze",
                "Atemschutz Überwachungstafel",
                "Heumessgerät"
            ],
            "Dach": [
                "Steckleiter 4-teilig",
                "Schiebeleiter",
                "Monsunrohr",
                "Rettungsring",
                "Einreißhaken",
                "Hakenleiter",
                "Kombileiter",
                "Heugabel",
                "Dunggabel",
                "Breithaue",
                "Feuerpatsche",
                "Schlauchbrücke",
                "Krampen",
                "Fassschaufel",
                "Randschaufel",
                "Sappine",
                "Spaten",
                "Notfalltank",
                "Auffangbehälter",
                "Besen",
                "Axt"
            ]
        },
        "Leiter": {
            "Mannschaft": [
                "Hochsichtbare Überwurfweste",
                "Anhaltekelle",
                "Meldertasche",
                "Einweghandschuhe",
                "Handscheinwerfer",
                "Warnlichthaube f. Handscheinwerfer",
                "Handlampe",
                "Handfunkgerät",
                "Mobilfunkgerät",
                "Suchscheinwerfer",
                "Arbietsmesser",
                "Verbandskasten",
                "Pannendreieck",
                "Entfernungsmesser",
                "Schutzhandschuhe",
                "Schlüssel"
            ],
            "Korb": [
                "Druckschlauch C 7 m",
                "Hohlstrahlrohr"
            ],
            "G1": [
                "Baufolie 4 x 4 m",
                "Korbtrage",
                "Schaufeltrage",
                "Schnittschutzhelm",
                "Schnittschutzhose",
                "Schnittschutzjacke",
                "E-Motorsäge",
                "Ersatzkette f. Motorsäge",
                "Ölkanister",
                "Bogensäge",
                "Halligantool",
                "FW-Doppelaxt",
                "Hacke kurz",
                "Handhammer 2 kg",
                "Krankentrage 2-teilig",
                "Schwerlastaufnahme",
                "Arbeitsleine",
                "Schnürleine",
                "Sturmleine",
                "Reifenfüllschlauch",
                "KFZ Werkzeug",
                "KFZ Starthilfekabel"
            ],
            "G2": [
                "Notrettungsset",
                "Basisausrüstung z. Halten v. Personen",
                "Rettungsdecke",
                "Rettungsleine 30 m",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Reserveflasche",
                "Brandfluchthaube",
                "Safty Peak"
            ],
            "G3": [
                "ABC Kupplungsschlüssel",
                "Druckschlauch B75 25 m orange",
                "Druckschlauch B75 20 m",
                "Druckschlauch C52 15 m",
                "Schlauchbinde C52",
                "Schlauchbinde B75",
                "Gurtschlauchhalter",
                "Druckbegrenzungsventil",
                "Überflurhydrantenschlüssel",
                "Übergangsstück B75-C52",
                "Verteiler B-CBC",
                "Flankierer",
                "Schlauchträger",
                "Schlauchbrücke"
            ],
            "G4": [
                "Flutlichtscheinwerfer 1000 W",
                "Dreibeinstativ",
                "Kabeltrommel 230 V",
                "Sprungpolster",
                "Rollgliss",
                "Werkzeugsatz i. Trage",
                "Absturzsicherungsgerät",
                "Verbindungsmittel 15 Vario",
                "FW-Gurt"
            ],
            "G5": [
                "Löschdecke",
                "ABC Pulverlöscher",
                "Verkehrsleitkegel",
                "Warndreieck \"Feuerwehr\"",
                "Absperrband"
            ],
            "G6": [
                "Schäkel 6,5 t",
                "Abschleppseil",
                "Wagenheber 10 t",
                "Schneeketten",
                "Kanister",
                "Einfüllstutzen"
            ],
            "Dach": [
                "Stromerzeuger",
                "Abgasschlauch",
                "Benzinkanister 10 l",
                "Überdruckentlüfter",
                "Rollgliss Bügel",
                "Safety Peak Bügel",
                "Wenderohr",
                "Aufnahme f. Korbtrage"
            ]
        },
        "Tank2": {
            "Fahrer/GK": [
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Wärmebildkamera",
                "Handlampe",
                "Personen-Sicherungsset",
                "Handfunkgerät",
                "Gasmessgerät"
            ],
            "Mannschaft": [
                "Handfunkterät",
                "Atemschutz Überwachungstafel",
                "Nothammer",
                "Pannendreieck",
                "Fahrzeugwerkzeug",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Reserveflasche",
                "Schutzhandschuhe",
                "Arbeitsmesser",
                "Verbandskaste",
                "Bergetuch",
                "Rettungsleine",
                "Steigergurt",
                "Meldertasche",
                "Handlampe",
                "Anhaltekelle",
                "Signaltaschenlampe",
                "Suchscheinwerfer",
                "Warndreieck \"Feuerwehr\"",
                "Absperrband",
                "Einweghandschuhe"
            ],
            "G1": [
                "Faltbehälter 3000 l",
                "Spiralluton",
                "Wasserwerfer",
                "Hydrofix",
                "Tauchpumpe",
                "Verlängerungskabel",
                "Be- u. Entlüftungsgerät"
            ],
            "G2": [
                "Hacke langstielig",
                "Hacke kurzstielig",
                "Hammer 2 kg",
                "Rauchfangschlüsselsatz",
                "Schachthakensatz",
                "Bogensäge",
                "Schnittschutzhose",
                "Motorkettensäge",
                "Treibstoff-Ölkanister",
                "Werkzeugkiste",
                "Lichtfluter 1000 W",
                "Flutbrücke",
                "KSA 20 m. Stromverteiler",
                "E-Werkzeug",
                "Kabeltrommel 230 V",
                "Generator 8 kVA",
                "Lichtmastbetätigung",
                "Haue",
                "Stativ",
                "Abgasschlauch",
                "Hammer 5 kg",
                "Brechstange",
                "Sappine",
                "Mistgabel",
                "Heugabel",
                "Ausräumhaken",
                "Piassava-Besen",
                "Flachschaufel",
                "Stichschaufel",
                "Trassenband",
                "Bolzenschneider",
                "Krampe",
                "Feuerwehraxt"
            ],
            "G3": [
                "Feuerlöscher",
                "Kaminkehrerwerkzeug",
                "Sammelstück BBB-A",
                "Hitzeschutzanzug",
                "Schutzanzug Schutzstufe 2",
                "Robisrohr m. Schlauch",
                "Hydroschild C",
                "Hydroschild B"
            ],
            "G4": [
                "Druckschlauch B",
                "Ölbindemittel",
                "Gummistiefel m. Stiefelsocken",
                "Seilstropp verz.",
                "Abschleppseil",
                "E-Gummimatte",
                "Plastikfolie",
                "Arbeitsleine",
                "Schnürleine"
            ],
            "G5": [
                "Druckschlauch C42",
                "Hohlstrahlrohr",
                "Verteiler B-CBC",
                "Kupplungsschlüssel",
                "Übergangsstück B-C",
                "Strahlrohr B m. Stützkrümmer",
                "Stützkrümmer",
                "Strahlrohr B",
                "Einlaufkrümmer B",
                "Druckbegrenzungsventil",
                "Flankierer",
                "Sammelstück BB-A",
                "Schlauchtragekorb",
                "Schaumrohr",
                "Zumischer Z2/Z4"
            ],
            "G6": [
                "Benzinkanister",
                "Dieselkanister",
                "Einfüllstutzen",
                "Hochdruckhaspel m. Pistole",
                "Druckschlauch HD",
                "Druckschlauch B",
                "Schlauchbrücke",
                "Fahrzeug Unterlegkeile"
            ],
            "Heck": [
                "Übergangsstück B-C",
                "Hydrantenschlüssel",
                "Handfunkgerät",
                "ABC-Kupplungsschlüssel",
                "Übergangsstück A110-B75",
                "Übergangsstück A125-A110",
                "Kupplungsschlüssel 125"
            ],
            "Dach": [
                "Schaumausrüstung",
                "Steckleiter 4-teilig",
                "Wasserwerfer",
                "Löschlanze",
                "Monsunrohr",
                "Einreißhaken"
            ]
        },
        "Tunnel": {
            "Fahrer/GK": [
                "Handfunkgerät",
                "Handlampe",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Suchscheinwerfer",
                "Meldertasche",
                "Gasmessgerät",
                "Tablet"
            ],
            "Mannschaft": [
                "Handfunkgerät",
                "Wärmebildkamera",
                "Schlüsselkasten",
                "Handlampe",
                "Atemschutz Überwachungstafel",
                "Information \"Gefährliche Stoffe\"",
                "Schreibmaterial",
                "Arbeitsmesser",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Notrettungsset",
                "Rettungsleine",
                "Brandfluchthaube",
                "Erste-Hilfe Rucksack",
                "Wolldecke",
                "Alu-Rettungsdecke",
                "Feuerwehrgurt",
                "Sauerstoff-Selbstretter",
                "Suchstock",
                "Einweghandschuhe",
                "Schutzhandschuhe",
                "Hochsichtbare Überwurfweste",
                "Anhaltekelle",
                "Set Powerflares"
            ],
            "G1": [
                "Teleskopleiter",
                "Arbeitsleine",
                "Schnürleine",
                "Trennschleifer",
                "Säbelsäge",
                "Schutzbrille",
                "FFP2-Maske",
                "Müllsack",
                "Schutzdecke",
                "Stabfast",
                "Schwelleraufsatz",
                "Unterleghölzer",
                "Notfallwanne",
                "Glasmanagement Set",
                "Airbag Sicherung",
                "Verlängerungskabel 10 m",
                "Werkzeugkiste",
                "StabPacks",
                "NATO-Kabel"
            ],
            "Tiefraum1": [
                "Abschleppseil",
                "Schäckel 65 kN",
                "Dieselkanister 20 l",
                "Einfüllstutzen"
            ],
            "G2": [
                "Sichtschutz",
                "Druckschlauch C",
                "Ölbindemittelkanister",
                "Handscheinwerfer",
                "Verkehrsleitkegel",
                "Warndreieck \"Feuerwehr\"",
                "Absperrband",
                "Stativ",
                "Kabeltrommel 230 V",
                "LED-Schweinwerfer",
                "Warnblitzleuchte",
                "RIS-Beleuchtungssystem",
                "ABC-Kupplungsschlüssel",
                "Notkurbel HD-Haspel",
                "Lichtmaststeuerung",
                "Drucklöschgerät Bioversal",
                "ABC-Pulverlöscher",
                "Löschanlage"
            ],
            "Tiefraum2": [
                "KFZ Unterlegkeile",
                "Löschdecke",
                "Stromgenerator"
            ],
            "G3": [
                "Schleifkorbtrage",
                "Schaufeltrage",
                "Akku Kombigerät",
                "Akku Spreizer",
                "Akku Schere",
                "Akku Zylinder",
                "Zylinder Verlängerung",
                "Zylinder Unterlegsgestell",
                "Akkuladegerät",
                "Notstromkabel f. Schere/Spreizer",
                "Brechstange",
                "Handhammer",
                "Bolzenschneider",
                "Besen",
                "Flachschaufel",
                "Hacke kurz",
                "Halligan Tool",
                "Doppelaxt",
                "Türbrecheisen",
                "Rettungswerkzeug",
                "Schneekette",
                "Schwelleraufsatz",
                "Zubehör Schere/Spreizer",
                "Anhängekupplung Kugelkopf",
                "Anhängekupplung Maulkupplung",
                "Adapter 7/13-Pol"
            ]
        },
        "Tunnel+Ölanh.": {
            "Fahrer/GK": [
                "Handfunkgerät",
                "Handlampe",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Suchscheinwerfer",
                "Meldertasche",
                "Gasmessgerät",
                "Tablet"
            ],
            "Mannschaft": [
                "Handfunkgerät",
                "Wärmebildkamera",
                "Schlüsselkasten",
                "Handlampe",
                "Atemschutz Überwachungstafel",
                "Information \"Gefährliche Stoffe\"",
                "Schreibmaterial",
                "Arbeitsmesser",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Notrettungsset",
                "Rettungsleine",
                "Brandfluchthaube",
                "Erste-Hilfe Rucksack",
                "Wolldecke",
                "Alu-Rettungsdecke",
                "Feuerwehrgurt",
                "Sauerstoff-Selbstretter",
                "Suchstock",
                "Einweghandschuhe",
                "Schutzhandschuhe",
                "Hochsichtbare Überwurfweste",
                "Anhaltekelle",
                "Set Powerflares"
            ],
            "G1": [
                "Teleskopleiter",
                "Arbeitsleine",
                "Schnürleine",
                "Trennschleifer",
                "Säbelsäge",
                "Schutzbrille",
                "FFP2-Maske",
                "Müllsack",
                "Schutzdecke",
                "Stabfast",
                "Schwelleraufsatz",
                "Unterleghölzer",
                "Notfallwanne",
                "Glasmanagement Set",
                "Airbag Sicherung",
                "Verlängerungskabel 10 m",
                "Werkzeugkiste",
                "StabPacks",
                "NATO-Kabel"
            ],
            "Tiefraum1": [
                "Abschleppseil",
                "Schäckel 65 kN",
                "Dieselkanister 20 l",
                "Einfüllstutzen"
            ],
            "G2": [
                "Sichtschutz",
                "Druckschlauch C",
                "Ölbindemittelkanister",
                "Handscheinwerfer",
                "Verkehrsleitkegel",
                "Warndreieck \"Feuerwehr\"",
                "Absperrband",
                "Stativ",
                "Kabeltrommel 230 V",
                "LED-Schweinwerfer",
                "Warnblitzleuchte",
                "RIS-Beleuchtungssystem",
                "ABC-Kupplungsschlüssel",
                "Notkurbel HD-Haspel",
                "Lichtmaststeuerung",
                "Drucklöschgerät Bioversal",
                "ABC-Pulverlöscher",
                "Löschanlage"
            ],
            "Tiefraum2": [
                "KFZ Unterlegkeile",
                "Löschdecke",
                "Stromgenerator"
            ],
            "G3": [
                "Schleifkorbtrage",
                "Schaufeltrage",
                "Akku Kombigerät",
                "Akku Spreizer",
                "Akku Schere",
                "Akku Zylinder",
                "Zylinder Verlängerung",
                "Zylinder Unterlegsgestell",
                "Akkuladegerät",
                "Notstromkabel f. Schere/Spreizer",
                "Brechstange",
                "Handhammer",
                "Bolzenschneider",
                "Besen",
                "Flachschaufel",
                "Hacke kurz",
                "Halligan Tool",
                "Doppelaxt",
                "Türbrecheisen",
                "Rettungswerkzeug",
                "Schneekette",
                "Schwelleraufsatz",
                "Zubehör Schere/Spreizer",
                "Anhängekupplung Kugelkopf",
                "Anhängekupplung Maulkupplung",
                "Adapter 7/13-Pol"
            ],
            "Ölanh. G1": [
                "Verkehrsleitkegel",
                "Erdspieß",
                "Warndreieck \"Öleinsatz\"",
                "Auffangwanne m. Ausguss",
                "Ölschlange",
                "Warntafel"
            ],
            "Ölanh. G2": [
                "Abfüllschaufeln f. Ölbindemittel",
                "Universal Ölbindemittel",
                "Spannringfass 60 l",
                "Besen",
                "Alu-Schaufel",
                "Bindemittel Streuwagen",
                "Auffangwanne 150 l",
                "Arbeitsleine",
                "Schnürleine",
                "Spillbag 15",
                "Ölbindemittel Reservesack",
                "Ölschlange",
                "Schachtabdeckung",
                "Chemische Bindemittel",
                "Bindeflies Rolle",
                "Spilltech Öl-Absorbent 1,2 m",
                "Schutzanzug",
                "Chemische Schutzhandschuhe",
                "Leckdichtpaste",
                "Selbstschweißendes Dichtband",
                "Plane 3 x 4 m"
            ]
        },
        "Pumpe": {
            "Fahrer/GK": [
                "Handfunkgerät",
                "Anhaltekelle",
                "Meldertasche m. Zubehör",
                "Schlüsselkasten",
                "Suchscheinwerfer"
            ],
            "Mannschaft": [
                "Arbeitsmesser",
                "Pressluftatmer",
                "Vollmaske f. Pressluftatmer",
                "Reserveflasche",
                "Handlampe",
                "Atemschutzfilter",
                "FW-Gurt",
                "Rettungsleine",
                "Notrettungsset",
                "Sicherungsgeschirr",
                "Sanitätskasten",
                "Wolldecke",
                "Handscheinwerfer",
                "Warndreieck \"Feuerwehr\"",
                "Hochsichtbare Überwurfweste",
                "Schutzhandschuhe",
                "Erste-Hilfe-Koffer",
                "Pannendreieck",
                "Wagenheber",
                "Warnlichthaube \"orange\"",
                "Feuerwehrbeil",
                "Bordwerkzeug",
                "Halteseil",
                "Kippstange",
                "Stützstange",
                "Bergetuch",
                "Starterkabel"
            ],
            "G1": [
                "Saugkorb",
                "Schutzkorb f. Saugkorb",
                "ABC-Kupplungsschlüssel",
                "Leinensatz",
                "Sammelstück",
                "Übergnagsstück B-C",
                "Übergnagsstück A-B",
                "Druckbegrenzungsventil",
                "Werkzeug f. TS",
                "Motorkettensäge",
                "Werkzeug f. Motorkettensäge",
                "Kombikanister",
                "Schnittschutzhose",
                "Greifzug 30 kN",
                "Greifzugseil",
                "Leichtklappklobe",
                "Ölbindemittel",
                "Tragkraftspritze",
                "Tauchpumpe",
                "Forsthelm",
                "Keil",
                "Wathose",
                "Rundschlinge",
                "Schäkel",
                "Standrohr",
                "Unterflurhydrantenschlüssel",
                "Saugschlauch A"
            ],
            "G2": [
                "Bolzenschneider",
                "Hacke langstielig",
                "Hacke kurzstielig",
                "Handhammer 2 kg",
                "Vorschlaghammer 5 kg",
                "Zimmermannshammer",
                "Schachthakensatz",
                "Rauchfangschlüsselsatz",
                "Tragkraftspritze",
                "Werkzeugkiste",
                "Krampe",
                "Brecheisen",
                "Brechstange",
                "Schneeketten",
                "Hubwinde",
                "Stahlseilstropp 5 m",
                "Stahlseilstropp 2,5 m",
                "Abschleppseil",
                "Kettengehänge",
                "Tauchpumpe",
                "Besen",
                "Schaufel",
                "Bogensäge",
                "Feuerwehraxt",
                "Kescher",
                "Eisensäge",
                "Ratschnesatz",
                "Absperrband",
                "ABC-Kupplungsschlüssel",
                "Saugkorb",
                "Schutzkorb f. Saugkorb",
                "Leinensatz",
                "Sammelstück",
                "Übergangsstück B-C",
                "Übergangsstück A-B",
                "Druckbegrenzungsventil",
                "Werkzeug f. TS"
            ],
            "G3": [
                "Druckschlauch B",
                "Druckschlauch C",
                "Schlauchtragekorb",
                "Hohlstrahlrohr",
                "Stützkrümmer B",
                "Überflurhydrantenschlüssel",
                "Übergnagstück 110-125",
                "Kupplungsschlüssel 125",
                "Übergangsstück B-C",
                "Übergangsstück A-B",
                "Verteiler B-CBC",
                "Hydroschild C",
                "Pulverlöscher ABC 12 kg",
                "Löschdecke",
                "Mehrzweckstrahlrohr B",
                "Schlauchbinden",
                "Homelite-Pumpe",
                "Dieselkanister 20 l",
                "Benzinkanister 20 l",
                "Saugschlauch B",
                "Einfüllstutzen",
                "Unterflurhydrantenschlüssel",
                "Arbeitsleine",
                "Schnürleine",
                "Schlauchknickschutz",
                "Rohrkrümmer",
                "Flankierer",
                "KFZ Unterlegkeile",
                "Saugschlauch A",
                "Saugkopf B",
                "Kupplungsschlüssel B-C",
                "Trichter",
                "CO2 Löscher",
                "Segeltucheimer"
            ],
            "G4": [
                "KSA 20",
                "Druckschlauch B",
                "Stromerzeuger MAG",
                "Stromerzeuger klein",
                "Abgasschlauch",
                "Verlängerungskabel 10 m",
                "Lichtfluter 1000 W",
                "Fluterbrücke",
                "Stativ 5 m",
                "Stativ 1,7 m",
                "Kunststofffolie",
                "Müllsack",
                "Kabeltrommel 230 V"
            ],
            "Heck": [
                "Schlauchladen B",
                "Schlauchbrücken",
                "Kupplungsschlüssel B-C",
                "Sappine",
                "Dunggabel",
                "Heugabel",
                "Dungkralle",
                "Atemschutz Überwachungstafel",
                "Einreißhaken",
                "Feuerpatsche"
            ],
            "Dach": [
                "Schiebeleiter 2-teilig",
                "Steckleiter 4-teilig",
                "Steckleiter Verbindungsteil",
                "Flachansauger"
            ]
        }
    }