class Settings:
    def __init__(self) -> None:

        ## firetruck
        self.FIRETRUCK_TRAINING_FEEDBACK_SEC = 2.0
        self.FIRETRUCK_TRAINING_WITH_IMAGES_FEEDBACK_SEC = 2.5
        self.FIRETRUCK_TRAINING_CORRECT_POINTS = 1
        self.FIRETRUCK_TRAINING_STRIKE_FACTOR = 50
        self.FIRETRUCK_GAME_INTERVAL_SEC = 0.1
        self.FIRETRUCK_GAME_DISPLAY_EXTRA_TIME_SEC = 2
        self.FIRETRUCK_GAME_START_TIME_SEC = 15.0
        self.FIRETRUCK_GAME_EXTRA_TIME_SEC = 10.0
        self.FIRETRUCK_GAME_FEEDBACK_SEC = 0.5
        self.FIRETRUCK_GAME_CORRECT_FOR_EXTRA_TIME = 5
        self.FIRETRUCK_GAME_CORRECT_POINTS = 100

        ## competition
        self.COMPETITION_GAME_INTERVAL_SEC = 0.1
        self.COMPETITION_GAME_DISPLAY_EXTRA_TIME_SEC = 2
        self.COMPETITION_GAME_START_TIME_SEC = 90.0
        self.COMPETITION_GAME_EXTRA_TIME_SEC = 60.0
        self.COMPETITION_GAME_FEEDBACK_SEC = 1.5
        self.COMPETITION_GAME_CORRECT_FOR_EXTRA_TIME = 4
        self.COMPETITION_GAME_CORRECT_POINTS = 100
